---
title: "Confidence Intervals (Debany)"
author: "Rachel Roggenkemper"
format: html
editor: visual
---

# Confidence Interval for M (total number of successes)

```{r}
COMBGLN <- function(a, b) {
  return(lgamma(a + 1) - (lgamma(b + 1) + lgamma(a - b + 1)))
}


NEG_HYPERGEO_PMF <- function(m, x, r, N) {
  if (m < 1 || m > r || m > x || N < 1 || r < 0 || r > N - x + m) {
    return(0)
  }
  return(exp(COMBGLN(x - 1, m - 1) + COMBGLN(N - x, r - m) - COMBGLN(N, r)))
}


NEG_HYPERGEO_SUM_N <- function(m, x_lo, x_hi, r, N) {
  total = 0
  for (x in x_lo:x_hi) {
    total = total + NEG_HYPERGEO_PMF(m, x, r, N)
  }
  return(total)
}


NEG_HYPERGEO_LB <- function(m, x, N, prob) {
  if (x == N) {
    return(m)
  }
  r_lo = m
  r_hi = N - x + m
  while (r_hi - r_lo > 0.001) {
    r = (r_lo + r_hi) / 2
    if (NEG_HYPERGEO_SUM_N(m, 1, x, r, N) < prob) {
      r_lo = r
    } else {
      r_hi = r
    }
  }
  return(r)
}


NEG_HYPERGEO_UB <- function(m, x, N, prob) {
  if (x == N) {
    return(m)
  }
  r_lo = m
  r_hi = N - x + m
  while (r_hi - r_lo > 0.001) {
    r = (r_lo + r_hi) / 2
    if (NEG_HYPERGEO_SUM_N(m, x, N, r, N) > prob) {
      r_lo = r
    } else {
      r_hi = r
    }
  }
  return(r)
}


CI <- function(m, x, N, alpha) {
  prob = alpha / 2
  CI_lb = NEG_HYPERGEO_LB(m, x, N, prob)
  CI_ub = NEG_HYPERGEO_UB(m, x, N, prob)
  
  CL = (1 - alpha) * 100
  return(cat(CL, "% Confidence Interval for M: [", CI_lb, ",", CI_ub, "]\n"))
}
```

```{r}
CI(m = 3, x = 1, N = 50, alpha = 0.05)
CI(m = 3, x = 2, N = 50, alpha = 0.05)
CI(m = 3, x = 3, N = 50, alpha = 0.05)
CI(m = 3, x = 4, N = 50, alpha = 0.05)
CI(m = 3, x = 5, N = 50, alpha = 0.05)
CI(m = 3, x = 6, N = 50, alpha = 0.05)
CI(m = 3, x = 7, N = 50, alpha = 0.05)
CI(m = 3, x = 8, N = 50, alpha = 0.05)
CI(m = 3, x = 9, N = 50, alpha = 0.05)
CI(m = 3, x = 10, N = 50, alpha = 0.05)
CI(m = 3, x = 11, N = 50, alpha = 0.05)
CI(m = 3, x = 12, N = 50, alpha = 0.05)
CI(m = 3, x = 13, N = 50, alpha = 0.05)
CI(m = 3, x = 14, N = 50, alpha = 0.05)
CI(m = 3, x = 15, N = 50, alpha = 0.05)
CI(m = 3, x = 16, N = 50, alpha = 0.05)
CI(m = 3, x = 17, N = 50, alpha = 0.05)
CI(m = 3, x = 18, N = 50, alpha = 0.05)
CI(m = 3, x = 19, N = 50, alpha = 0.05)
CI(m = 3, x = 20, N = 50, alpha = 0.05)
CI(m = 3, x = 21, N = 50, alpha = 0.05)
CI(m = 3, x = 22, N = 50, alpha = 0.05)
CI(m = 3, x = 23, N = 50, alpha = 0.05)
CI(m = 3, x = 24, N = 50, alpha = 0.05)
CI(m = 3, x = 25, N = 50, alpha = 0.05)
CI(m = 3, x = 26, N = 50, alpha = 0.05)
CI(m = 3, x = 27, N = 50, alpha = 0.05)
CI(m = 3, x = 28, N = 50, alpha = 0.05)
CI(m = 3, x = 29, N = 50, alpha = 0.05)
CI(m = 3, x = 30, N = 50, alpha = 0.05)
CI(m = 3, x = 31, N = 50, alpha = 0.05)
CI(m = 3, x = 32, N = 50, alpha = 0.05)
CI(m = 3, x = 33, N = 50, alpha = 0.05)
CI(m = 3, x = 34, N = 50, alpha = 0.05)
CI(m = 3, x = 35, N = 50, alpha = 0.05)
CI(m = 3, x = 36, N = 50, alpha = 0.05)
CI(m = 3, x = 37, N = 50, alpha = 0.05)
CI(m = 3, x = 38, N = 50, alpha = 0.05)
CI(m = 3, x = 39, N = 50, alpha = 0.05)
CI(m = 3, x = 40, N = 50, alpha = 0.05)
CI(m = 3, x = 41, N = 50, alpha = 0.05)
CI(m = 3, x = 42, N = 50, alpha = 0.05)
CI(m = 3, x = 43, N = 50, alpha = 0.05)
CI(m = 3, x = 44, N = 50, alpha = 0.05)
CI(m = 3, x = 45, N = 50, alpha = 0.05)
CI(m = 3, x = 46, N = 50, alpha = 0.05)
CI(m = 3, x = 47, N = 50, alpha = 0.05)
CI(m = 3, x = 48, N = 50, alpha = 0.05)
CI(m = 3, x = 49, N = 50, alpha = 0.05)
CI(m = 3, x = 50, N = 50, alpha = 0.05)
```
